trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'backend/pom.xml'
    goals: 'clean package -DskipTests'

- task: Docker@2
  inputs:
    command: buildAndPush
    repository: amazonbooks-backend
    dockerfile: backend/Dockerfile
    containerRegistry: dockerhub-service-connection
    tags: |
      latest
      $(Build.BuildId)
